[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "example"
version = "0.0.1"

[tool.scikit-build]
wheel.packages = ["foo", "bar"]
sdist.exclude = ["*.c"]
